### PR TITLE
Application of Ofsted urn linking

### PR DESCRIPTION
**Pull request by pchapman267**
Hi Adam,

I have taken fix attempt branch and applied Pennie's Ofsted linking to the code. More detailed comments in commits.

Biggest issue identified - select inspection with only 9s isn't useful, created a sum of sub-categories that will take smallest - i.e. fewest 9s.

If you need more info, please let me know.

### CODE REVIEW

**Comment by pchapman267** [comment]
@adamrobinson361  

I have added the linking code for Ofsted linking and updated the main code to make use of this, in addition to added status code and history order variables. I am not sure why Travis isn't checking these though.

**Comment by adamrobinson361** [comment]
Thanks for the pull request @pchapman267 - I've been going through this and there is quite a lot in there! Lots of good stuff and great that you and Pennie have worked out this methedology! 

To get this merged I think generally it could do with a bit of restructuring and in particular commenting so that it fits more nicely into the overall project. I think its "purposefully" keeping my old stuff and adding the new at the moment but I think the idea is that we just want to move towards yours/Pennies method. I'm happy to do the restructuring and will open a separate pull request for that with some simplifications where possible. 

Some general advice would be to make names more meaningful and comment each code chunk so that it's easier to review.

I've got one outstanding question from my side:

1. **What is the ofsted_urn_links data frame and file?** - My understanding is that the main part of the code is making predecessors2 which replaces my predecessors table. I'm not clear what the ofsted_urn_links file is for and why it has a separate while loop

I've currently deleted this in my own local working version as it seemed redundant apart from the writing of the file at the end but would be good to understand more about this.

**Comment by adamrobinson361** [comment]
Also worth flagging for my own benefit that I get some weird numbers in the history order call in all_data_final. I'll do some more digging,

Cheers,

Adam

**Comment by pchapman267** [comment]
Hi @adamrobinson361,

So there are two end uses that I see:
- Your method which looks back at any school which uses predecessors
- Methodology to look at only currently open schools

If you want to update any URN to Current URN directly, that is what ofsted_urn_links allows you to do. So old census data could be merged on Ofsted data frame (filter to GIAS status code 1 and 3).

Equally, the full output allows you to match onto Ofsted of any school for at point in time, which URN it has and see its prior inspections.

The redundancy was more to keep both of these subsets alive to allow people the choice of an all links and a CurrentURN links depending on the work that needs to be undertaken. For majority of my work, predecessors links wouldn't help me but CurrentURN links is a massive assistance when trying to see what a current school has done in the past. This might be my desire that the one code set works greatest set of users - within TAD and potentially wider.

Apologies for lack of comments - completely my issue that I had to strip the code out of Rmarkdown file that Pennie created, as it wouldn't run on my computer. So it lost the Rmarkdown comments. I can try to add back in.

When I looked at Ofsted history order, it looked fine once I had re-ordered the column to look at URN and then publication date - though happy to be wrong and be corrected.

Hope this rambling makes some sense as it is late and my brain is not fully operational. Happy to discuss if it helps.

**Comment by adamrobinson361** [comment]
@pchapman267 - I've been through this in-depth now and think we're nearly there :)

I've made the following changes local on my laptop to in part quality assure and in part align/ finalise the code so it fits in with the rest of the project:

- Added comments to ofsted urn linking.
- made some of the names of objects more verbose to give a hint what they are.
- Moved the filtering of successor links to one pipe.
- Renamed ofsted_urn_links to current_urn and moved to end of script (made clear it is a by-product) hence being at the end.
- Renamed predecessors2 to predecessors to flag this is now the only method.

Can you confirm you're happy with these changes. If so I'll push the up for a final review.

Cheers,

Adam

**Comment by adamrobinson361** [comment]
@pchapman267 - i've prematurely pushed the changes as the code is on my home computer and i'm going to need a version of this on work computer tomorrow. 

The differences show as i've removed all the old and put all new but thats not the case - i think git is just not registering it properly. 

Can you take a read through the ofsted urn linking file and confirm you are happy. I've not changed any of the code - just comments, naming and a bit of restructuring to make it cleaner.

Cheers,

Adam

**Comment by pchapman267** [comment]
Apologies @adamrobinson361 , only just spotted this. I had some urgent work for ECF and didn't flag the speed need for this. Could you please let me know if you still need this done quickly (and time to done by) or if my other priority work can to precedence for now?

**Comment by pchapman267** [comment]
Hi @adamrobinson361, just read through the code as the compare changes wasn't highlighting properly as you mentioned. All looks good to me.

**Comment by adamrobinson361** [comment]
Nice one thanks @pchapman267 🙂

I’ll approve based on that. Let’s take another look once ofsted starts again as it should automatically work then ,

Adam

**Pull request merged**
