### PR TITLE
Fix attempt

### PR DESCRIPTION
**Pull request by pchapman267**
Ofsted framework change means that 1:1 relation no longer exist.
Quality of teaching..., personal development, behaviour and welfare, outcomes are no longer filled and now NA
Quality of education, behavior and attitudes, personal development has now created and have actual rating for inspections from now on.

Code ensures the columns are all created and filled with NAs where appropriate.
Column amended names also included - short changes to section 8, ordering of safeguarding title

### CODE REVIEW

**Comment by adamrobinson361** [comment]
Cheers Paul - looks good. My only concern is about having NA/Null in the new columns as I imagine that makes it a little bit harder for analysis (always have to convert to something) and isn't consistent across all inspections (I noted that in the December 2019 extract they had put 9's in the new columns for latest inspections when they were on old framework).

What do you think about me putting the NA's set to 9 and then potentially add a new column that flags which framework we think the inspection is from based on the fields being populated?

**Comment by adamrobinson361** [comment]
Also, you mentioned in our chat that you thought one of the columns was taking its value from the wrong place - I don't see any change that changes a column? Do you remember where that is?

**Comment by pchapman267** [comment]
Hi Adam,

The value change was around line  328/326 
  it was showing:  outcomes_for_children_and_learners = early_years_provision,
  I changed to:   early_years_provision_where_applicable = early_years_provision,

I think the switching to 9s sounds like a good idea and have no problem with that at all. A new column with framework used would be nice, though might be harder to achieve (my knowledge of pre-2015 inspection frameworks is almost non-existent).

**Comment by pchapman267** [comment]
In testing offline with Pennie's links file, I have also tested switching to 9s which involved some trial and error around data types - which I can add into next branch.

**Comment by adamrobinson361** [comment]
@pchapman267 - looks like the line 328 change didn't come through. I've done again in a commit and also switched the NA's to 9's. 

You can see my specific changes by clicking on commits on this pull request and then scrolling down to the last commit and clicking on it. Otherwise you can go via this [link](https://github.com/dfe-analytical-services/ofsted/pull/6/commits/80b6e92342772e69fddcaeecf0178711e7a689af).

Does that look alright?

**Comment by pchapman267** [comment]
Hi @adamrobinson361 

I have had a look and made a couple of changes based on my offline testing, which was incorporated into using Ofsted URN linking. Are you happy using a text 9 for text Is_safeguarding_effective column?

Tested offline before:
Line 243: Is_safeguarding_effective can be run as text '9' - Is_safeguarding_effective input contains Yes, No, 9
Line 331: Is_safeguarding_effective can be run as text '9' - Is_safeguarding_effective input contains Yes, No, 9
Line 332 and 333: urn_at_time_of_latest_full_inspection and laestab_at_time_latest_full_inspection not converted to 9s earlier. Also converting to 9s doesn't work when running.

**Comment by adamrobinson361** [comment]
Hi Paul I've set it to 9 and removed your other changes. Best to get this one approved first and then do a separate PR for the other changes. Sorry I've not had chance to catch up with you yet!

With the 9 imputed as text are you happy with this to be approved?

**Comment by pchapman267** [comment]
I am not happy to approve as the code looks to have regressed multiple steps and thing it will no longer work. You seem to have removed most of the changes that we had agreed on previously.

**Comment by adamrobinson361** [comment]
Ah no :( - I must’ve made a mistake. Will have a look in a bit. I tried to do all the changes that we’d discussed plus the change of is safeguarding effective to 9. I removed the new stuff on linking types so we could look at that separately. I’m on my phone but u sure your looking in right place? Should be the files changed tab

**Comment by adamrobinson361** [comment]
If you are looking in right place then what are you expecting to see?

**Comment by pchapman267** [comment]
My bad - wrong code - but line 331 is still wrong - needs to '9' instead of NA. Otherwise, I think that might be it.

**Comment by pchapman267** [comment]
Apologies, for my mistake. Reading again lines 332 and 333 are also not correctly aligned with changes further up - URN and LAESTAB as NA, Safeguarding as '9'

**Comment by adamrobinson361** [comment]
Shouldve fixed those now 👍 I'll probs do another offline test and suggest maybe you do the same next week if you've got some time?

**Comment by pchapman267** [comment]
Yes, looks good to me :) It looks like my offline version - but I will try to test again before we merge - though I am being pivoted to gain some extra work next week. Is it worth a quick chat sometime next week? Hope you have a good weekend.

**Comment by adamrobinson361** [comment]
Yep sounds good to me then we can get it over the line. Feel free to pop
something in.

Have a good weekend too!

**Pull request merged**
